name: .NET Core [Pre-Release]

on:
  push:
    branches-ignore:
     - 'release/*'
     - 'hotfix/*'
    pull_request:
     - opened
     - edited
     - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch tags and master
      run: |
          git fetch --tags
          git branch --create-reflog master origin/master
          echo REF: $GITHUB_REF
          echo SHA: $GITHUB_SHA
          echo ::set-env name=GIT_BRANCH::$GITHUB_REF
    - name: Determine .net core version
      run: |
          echo .NET Core Version: `sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json`
          echo ::set-env name=DOTNET_VERSION::`sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json`
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: 3.1.102
    - name: Setup Nuget
      run: sudo apt-get install nuget
    - name: Install Build Version Tool
      run: nuget install FunFair.BuildVersion -ExcludeVersion -Source ${{ secrets.FUNFAIR_NUGET_FEED }}
    - name: Set Define Build Version
      run: dotnet FunFair.BuildVersion/lib/BuildVersion.dll  ${{ steps.buildnumber.outputs.build_number }}
    - name: Build with dotnet
      run: |
             cd src
             dotnet build --configuration Release /p:Version=${{ env.BUILD_VERSION }}
    - name: Publish tool
      run: |
             cd src
             dotnet publish --configuration=release -o ../prepublish/lib --no-build --no-restore /p:Version=${{ env.BUILD_VERSION }}
    - name: pack tool
      run: nuget pack prepublish/package.nuspec -tool -outputdirectory dist -version ${{ env.BUILD_VERSION }}
    - name: publish
      run: dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
