name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release /p:Version=1.0.0.${{ steps.buildnumber.outputs.build_number }} 
    - name: Pack tool 
      run: dotnet pack --configuration Release -o dist  --no-build --no-restore /p:Version=1.0.0.${{ steps.buildnumber.outputs.build_number }} 
    - name: publish
      run: dotnet nuget push dist/*.nupkg --user credfeto --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/credfeto/index.json
