name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack tool 
      run: dotnet pack --configuration Release -o dist
    - name: publish
      run: nuget push dist/*.nupkg -apikey ${{ secrets.GITHUB_TOKEN }} -source https://nuget.pkg.github.com/credfeto/index.json
