name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        dotnet-version: 3.0.100
    - name: Setup Nuget
      run: sudo apt-get install nuget
    - name: Build with dotnet
      run: dotnet build --configuration Release /p:Version=1.0.0.${{ steps.buildnumber.outputs.build_number }} 
    - name: Publish tool 
      run: dotnet publish --configuration=release -o prepublish/lib --no-build --no-restore /p:Version=1.0.0.${{ steps.buildnumber.outputs.build_number }}
    - name: pack tool
      run: nuget pack prepublish/package.nuspec -tool -outputdirectory dist
    - name: publish
      run: dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
